---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
  namespace: apps
spec:
  chart:
    spec:
      chart: meilisearch
      version: 0.20.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: meilisearch
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    command:
      - tini
      - --
      - /bin/meilisearch
      - --experimental-dumpless-upgrade
    environment:
      MEILI_ENV: production
      MEILI_LOG_LEVEL: WARN
      MEILI_NO_ANALYTICS: "true"
    auth:
      existingMasterKeySecret: meilisearch-secret
    persistence:
      enabled: true
      storageClass: ceph-block
      size: 10Gi
